kadai11
ShunsukeNakamura2/test pull request #11
Opened 2024-03-21 08:19 UTC by ShunsukeNakamura2

〇課題11
文字列を渡すと逆順にして返す関数を作成してください。
(漢字等の複数バイト文字を考慮する必要はありません)

関数プロトタイプ
void rev_str(char* str); 

よろしくお願いします。

2024-03-22 05:45 UTC, Ryusei-Ami requested changes

2024-03-22 05:45 UTC, Ryusei-Ami commented on kadai11/kadai11.c
> +    for(int i = 0; i < length / 2; i++) {
「length / 2」は、for文内で計算しないほうが良い。
forを評価するたびに計算が実施されるので、繰り返し数分無駄な計算コストがかかる。
可能な限り、定数の比較をすること。

2024-03-25 02:27 UTC, Ryusei-Ami approved these changes

2024-03-25 02:37 UTC, Ryuji-Aruga approved these changes

2024-03-25 03:09 UTC, merged