Kadai13
ShunsukeNakamura2/test pull request #13
Opened 2024-03-21 08:41 UTC by ShunsukeNakamura2

〇課題13
構造体DAT_tの配列をソートし表示してください。
ソート順は、nの値で昇順、nが同一の値の場合は
sの文字コードで昇順とします。
ソート処理にはC標準関数qsort()を使ってください。

よろしくお願いします。

2024-03-22 05:58 UTC, Ryusei-Ami requested changes

2024-03-22 05:58 UTC, Ryusei-Ami commented on kadai13/kadai13.c
> +        {10, "testB"},
課題（仕様）が「下記構造体の配列をソートし表示してください」なので、ここは変えたら駄目では？

2024-03-25 02:34 UTC, Ryusei-Ami requested changes
指摘に問題がある場合は、Slackでお知らせください。

2024-03-25 02:34 UTC, Ryusei-Ami commented on kadai13/kadai13.c
> +    } else if(strcmp(dat1->s, dat2->s) > 0) {
ここのelse if 以降の部分は、単純に「return strcmp(...)」では駄目ですか？
その方がstrcmp()も1回で済むので、低コストでは？

2024-03-25 02:52 UTC, Ryuji-Aruga approved these changes

2024-03-25 03:41 UTC, ShunsukeNakamura2 commented on kadai13/kadai13.c
> +    } else if(strcmp(dat1->s, dat2->s) > 0) {
strcmp() の戻り値をそのまま返すように修正しました。
指摘以前の部分に関しても処理を見直して修正しました。

2024-03-25 07:16 UTC, Ryusei-Ami requested changes

2024-03-25 07:16 UTC, Ryusei-Ami commented on kadai13/kadai13.c
> + * @retval < 0  n1が大
コメントあってます？

2024-03-25 07:16 UTC, Ryusei-Ami commented on kadai13/kadai13.c
> +        return dat1->n - dat2->n;
nの比較は、修正前の方が良いです（なので、そこは指摘しませんでした）。
よい機会なので、何故駄目かを理解し、リプライに回答した上で修正してください。

2024-03-26 02:28 UTC, ShunsukeNakamura2 commented on kadai13/kadai13.c
> +        return dat1->n - dat2->n;
構造体配列に{-2147483647, "A"}を入れて実行したところ、この要素が1番大きいと判定される結果になりました。
nの比較を修正前の判定に戻すことで、この要素が1番小さいと正常に判定されることを確認しました。

2024-03-27 01:47 UTC, Ryusei-Ami approved these changes

2024-03-27 02:49 UTC, merged