kadai14
ShunsukeNakamura2/test pull request #14
Opened 2024-03-22 06:46 UTC by ShunsukeNakamura2

〇課題14
コマンドラインで指定されたテキストファイルの内容を表示するプログラムを作成してください。
(文字コード以外のコードが含まれていた場合のことを考慮する必要はありません)

usage
プログラム名 filename 

よろしくお願いします。

2024-03-25 02:55 UTC, Ryusei-Ami requested changes

2024-03-25 02:55 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +    int error;
リターンコード用の変数はrcやretの用に、「戻り値」を意味する変数名にしたほうが良い。
「error」だとエラーコードだけを扱うように見えるが、L19ではerrorに正常な値を入れて評価しているので、エラーのみではない。

2024-03-25 02:55 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +    if((error = fopen_s(&fp, argv[1], "r")) == 0) {
製品開発を意識して、異常系を先に処理してください。
異常系を先に処理すると、可読性や保守性が向上し、ネストも浅くなります。
また、デバッガ処理を意識して、関数を条件分の外に出してください。
今の書き方だと、デバッガでerrorに任意の値を設定出来ない場合があります。

以下、修正例。

rc = fopen_s(...);
if (rc != 0) {
　エラー処理
}

2024-03-25 02:55 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        while(fgets(str, MAX_LEN, fp) != NULL) {
入力ファイルの一行のdataがMAX_LENより長い場合、どうなりますか？
この質問の返答は、この指摘のリプライコメントでOKです。

fgets()がエラーの場合、エラー処理がされません。

2024-03-25 02:55 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        fclose(fp);
fclose()のエラー処理が無いですが、意図的ですか？

2024-03-25 02:55 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        printf("file open error\nerror code:%d", error);
%dの後ろに改行入れた方が良いのでは？
デバッグすれば気づきそうですが、エラー系デバッグしてない？

2024-03-25 02:59 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +int main(int argc, char *argv[])
実行時引数が不足している場合はusageを出力してください。
多い場合は、正常実行で良いです。

2024-03-25 03:09 UTC, Ryuji-Aruga requested changes

2024-03-25 03:09 UTC, Ryuji-Aruga commented on kadai14/kadai14.c
> +
argcで引数が入力されているかどうかチェックした方が良いと思います。

2024-03-25 03:43 UTC, ShunsukeNakamura2 commented on kadai14/kadai14.c
> +        while(fgets(str, MAX_LEN, fp) != NULL) {
MAX_LENより後ろのデータは切り捨てられ、読み込まれません。

2024-03-25 03:59 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        while(fgets(str, MAX_LEN, fp) != NULL) {
> MAX_LENより後ろのデータは切り捨てられ、読み込まれません。
やはりそうでしたか。
課題14は一行の長さが不定なので、fgets()では駄目かと。
別の方法を検討してください。

2024-03-26 02:30 UTC, Ryusei-Ami requested changes

2024-03-26 02:30 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        buff = fgetc(fp);
実行結果は正しくなりますが、fgetc()で一文字づつ READ/WRITE するのはパフォーマンスが酷いのでやめましょう。製品開発に臨むエンジニアらしいプログラムにしたいので、open/read/write/close システムコールを使って書き直してください。
その際、ファイルアクセスは、すべてエラー処理を考慮してください。

2024-03-26 02:30 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +    int fopen_rc;
リターンコード用の変数は、特別な理由がない限り「int rc;」とかにして使いますのが一般的です。
そうしないと、判定毎のリターンコード変数が大量に必要になってしまいます。

2024-03-26 02:30 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        printf("file open error\nerror code:%d\n", fopen_rc);
エラーが発生した時に、リターンコードだけだと原因が判りにくいです。
リターンコードに対するエラーメッセージも出力してみてください（専用の関数があります）。

2024-03-27 02:15 UTC, Ryusei-Ami requested changes

2024-03-27 02:15 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        printf("file open error\nerror:%s (code:%d)\n", error_message, errno);
過去の指摘でprintf()の引数に関数を取らないよう指摘しましたが、strerror()はgetter的な関数なので、直接引数に使用して良いです。

2024-03-27 02:15 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        return 0;
別の課題で指摘していますが、エラー時の戻り値は0以外にしてください。

2024-03-27 02:15 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +    file = open(argv[1], O_RDONLY);
些末なことですが、ファイルディスクリプタとファイルは別物なので、変数名はfdとかのが良いです。fileと書くとファイル名とかと誤認されやすいです。

2024-03-27 02:15 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +            break;
read()がエラーになった時に、0以外を返却できるようにしてください。
close()も同様。

2024-03-27 02:15 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +        if(size == 0) {
sizeが0の場合はprintf()実行前に抜けるべきでは？

2024-03-27 02:15 UTC, Ryusei-Ami commented on kadai14/実行結果.txt
> +$ ./a input.tx
実行結果のエビデンスなので、実行ファイル名は揃えましょう。

2024-03-28 04:48 UTC, Ryuji-Aruga requested changes

2024-03-28 04:48 UTC, Ryuji-Aruga commented on kadai14/kadai14.c
> +
エラーコードを定義するなら成功(０)もあった方がいいです。

2024-03-29 00:28 UTC, Ryuji-Aruga approved these changes

2024-04-01 04:49 UTC, Ryusei-Ami requested changes
指摘はスペルミスだけです。
これが修正されたら、approveします。

2024-04-01 04:49 UTC, Ryusei-Ami commented on kadai14/kadai14.c
> +#define RETURN_NOMAL_END 0
綴りは正しく。
NOMAL→ NORMAL

2024-04-01 07:06 UTC, Ryusei-Ami approved these changes

2024-04-01 07:39 UTC, merged