kadai16
ShunsukeNakamura2/test pull request #16
Opened 2024-03-22 07:26 UTC by ShunsukeNakamura2

〇課題16
最下位ビットが立っているか調べる
関数マクロを作成してください。

マクロ
BITON(i) 

よろしくお願いします。

2024-03-25 04:09 UTC, Ryusei-Ami requested changes

2024-03-25 04:09 UTC, Ryusei-Ami commented on kadai16/kadai16.c
> +#define BITON(i) ((i) & 0b1)
「0b1」は「1」では駄目なのですか？（わざわざ難しい表現にしなくても良いかと）

2024-03-25 07:03 UTC, Ryuji-Aruga approved these changes

2024-03-26 02:31 UTC, Ryusei-Ami approved these changes

2024-03-26 05:45 UTC, merged