Kadai18
ShunsukeNakamura2/test pull request #17
Opened 2024-03-25 00:53 UTC by ShunsukeNakamura2

〇課題18
パラメータで渡されたファイルの16進ダンプを
表示するプログラムを作成してください。

usage: プログラム名 filename
options: filename  ファイル名 

出力例
$ ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
$ 00000000 01 02 03 41 42 43 20 5C 26 82 A0 83 41 B1 B2 82
$ 00000100 A2

2024-03-25 06:50 UTC, Ryusei-Ami requested changes

2024-03-25 06:50 UTC, Ryusei-Ami commented on kadai18/kadai18.c
> +int main(int argc, char *argv[])
これまでの指摘を元に、一旦修正してみてください。
入力パラメータチェック、usage出力、エラー処理あたりを考慮してみてください。

2024-03-25 08:00 UTC, Ryuji-Aruga requested changes

2024-03-25 08:00 UTC, Ryuji-Aruga commented on kadai18/kadai18.c
> +
アドレスは行数ですか？　16バイトずつ増えてくのが正しい気がします。
出力例で、00000100になっているのは間違いでは。

2024-03-27 02:30 UTC, Ryusei-Ami requested changes

2024-03-27 02:30 UTC, Ryusei-Ami commented on kadai18/Makefile
> +kadai18:
以下のサイトとかを参考に、書き直してください。
http://omilab.naist.jp/~mukaigawa/misc/Makefile.html
せめて、all、clean, $(PROGRAM) くらいは欲しい。

2024-03-28 05:24 UTC, Ryuji-Aruga approved these changes

2024-04-01 07:10 UTC, Ryusei-Ami requested changes

2024-04-01 07:10 UTC, Ryusei-Ami commented on kadai18/kadai18.c
> +#define RTURN_USAGE 1
スペルミス：RTURN

2024-04-01 07:10 UTC, Ryusei-Ami commented on kadai18/kadai18.c
> +#define RETURN_NOMAL_END 0
スペルミス：NOMAL

2024-04-01 07:10 UTC, Ryusei-Ami commented on kadai18/kadai18.c
> +        unsigned char output[OUTPUT_NUM] = {0};
変数宣言は、必ず「{」の直後にすること。
{}の中間に宣言すると、コンパイルエラーになる機種があります。

2024-04-01 07:10 UTC, Ryusei-Ami commented on kadai18/kadai18.c
> +            printf(MSG_FILE_ERROR, "read", strerror(errno), errno);
Slackでお伝えした「関数マクロ化」の追加課題です。
このprintf関数そのものをマクロ化してください。引数は最小限にしてください。

2024-04-03 00:48 UTC, Ryusei-Ami requested changes

2024-04-03 00:48 UTC, Ryusei-Ami commented on kadai18/kadai18.c
> +    printf(MSG_FILE_ERROR, #err, strerror(err), err)
MSG_FILE_ERRORは、マクロにする意味がないので、メッセージ直書きで良い。
#errは、今回のケースでは可読性が下がるのでやめたほうが良い。
「引数を最小限に」は、"close"等のoperation_nameを想定していた。
strerror(errno), errnoは引数取らなくても使えるので、これで引数が一つになるかと。

2024-04-05 08:44 UTC, Ryusei-Ami approved these changes

2024-04-08 05:11 UTC, merged