kadai17
ShunsukeNakamura2/test pull request #18
Opened 2024-03-25 00:58 UTC by ShunsukeNakamura2

〇課題17
パラメータで渡されたサイズ分メモリを確保する
プログラムを作成してください。
(パラメータsizeの値が格納するデータ型の
範囲外の値かチェックする必要はありません)

usage: プログラム名 size[M|K]
options: size[M|K]  サイズ(M=メガ,K=キロ) 

よろしくお願いします。

2024-03-25 04:21 UTC, Ryusei-Ami requested changes
他にも気になる点があるのですが、一旦ここまでの修正をみたいので、指摘を出します。

2024-03-25 04:21 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +int main(int argc, char *argv[])
実行時引数が不足している場合はusageを出力してください。
多い場合は、正常実行で良いです。

2024-03-25 04:21 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +    memory = malloc(size);
malloc()したら、必ずfree()しましょう。
open & close, malloc & free等、対になる処理は終了処理を必ず実行してください。

2024-03-25 04:21 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +
malloc() する前に、sizeをダンプしてみてください。
そして、いくつかのテストパターンを試して、その結果をアップロードしてください。

2024-03-25 07:35 UTC, Ryuji-Aruga requested changes

2024-03-25 07:35 UTC, Ryuji-Aruga commented on kadai17/kadai17.c
> +
変数はできるだけ初期化するようにしてください。
全ての課題を修正する必要はないです。

2024-03-25 07:57 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +    strncpy(size_char, argv[1], param_length - 1);
size_charは末尾がNUL文字じゃない可能性あり

2024-03-26 02:56 UTC, Ryusei-Ami requested changes

2024-03-26 02:56 UTC, Ryusei-Ami commented on kadai17/実行結果.txt
> +〇L56 時点での変数sizeをダンプ
誤解を招く伝え方ですいません。
./katai17 実行時にsizeが出力されるように、printf()を追加して欲しかったです。

2024-03-26 02:56 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +        char buff = argv[1][i];
argv[]を直接使い回すと、中身が直感的に分からず可読性が下がります。
「request_size_str = arg[1]」のように、変数に代入して使い回すと、変数名から用途が判り、可読性が向上します。

2024-03-26 02:56 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +        printf("usage: kadai17 size[M|K]\noptions: size[M | K]  サイズ(M = メガ, K = キロ)\n");
同じメッセージを複数箇所に書くと、保守性が下がります。
マクロをうまく使って、保守性を上げましょう。

2024-03-26 02:56 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +        return 0;
一般的に、正常系は0返却、異常系は0以外を返却します。
ですので、ここでは0以外を返却しましょう。

2024-03-26 02:56 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +        printf("Failed to allocate memory\n");
異常系なので、ここで異常値を返却しましょう。

2024-03-27 02:22 UTC, Ryusei-Ami requested changes

2024-03-27 02:22 UTC, Ryusei-Ami commented on kadai17/kadai17.c
> +    char *request_size_str = argv[1];
argcチェック前にセットするのは良くないです。
理由が判らない場合は、聞いてください。

2024-03-27 07:40 UTC, Ryusei-Ami approved these changes

2024-03-29 01:02 UTC, Ryuji-Aruga approved these changes

2024-03-29 05:45 UTC, merged