kadai19
ShunsukeNakamura2/test pull request #19
Opened 2024-03-25 02:55 UTC by ShunsukeNakamura2

〇課題19
指定したサイズのファイルを作成する
プログラムを作成してください。
(パラメータsizeの値が格納するデータ型の
範囲外の値かチェックする必要はありません)

usage: プログラム名 filename size[M|K]
options: filename  ファイル名
             size[M|K]  サイズ(M=メガ,K=キロ) 

よろしくお願いします。

2024-03-25 06:57 UTC, Ryusei-Ami requested changes

2024-03-25 06:57 UTC, Ryusei-Ami commented on kadai19/kadai19.c
> +int main(int argc, char *argv[])
これまでの指摘を元に、修正してみてください。
入力パラメータチェック、usage出力、エラー処理あたりを考慮してみてください。

2024-03-25 06:57 UTC, Ryusei-Ami commented on kadai19/kadai19.c
> +    for(int i = 0; i < size; i++) {
間違いでは無いのですが、「指定サイズのファイルを作成する」ことが条件ならば、スパースファイルで十分です。スパースファイル作成に書き換えてみてください。

2024-03-25 06:57 UTC, Ryusei-Ami commented on kadai19/実行結果.txt
> +$ ./a out 1K
単位の指定が無いケースの実行例も欲しいです。

2024-03-29 01:11 UTC, Ryuji-Aruga requested changes

2024-03-29 01:11 UTC, Ryuji-Aruga commented on kadai19/kadai19.c
> +
lseek()とwrite()も戻り値があると思いますので、チェックするようにしてみてください。

2024-03-29 06:00 UTC, Ryuji-Aruga approved these changes

2024-04-01 07:29 UTC, Ryusei-Ami requested changes
製品開発を意識したコーディング手法を習得するための指摘をします。
課題18にも同じ問題がありますが、そちらの修正は不要です。
課題18で実施する「関数のマクロ化」は、この課題では不要です。

2024-04-01 07:29 UTC, Ryusei-Ami commented on kadai19/kadai19.c
> +    } else {
正常系の処理をelseでネストし続けると、ネストが深くなるので、エラーケースはgotoでclose()の直前に飛ばしましょう。gotoタグはendにしましょう。
類似も同様です。

2024-04-01 07:29 UTC, Ryusei-Ami commented on kadai19/kadai19.c
> +            main_rc = RETURN_FAIL_SEEK_CLOSE;
エラーの混合ケースでコマンドの戻り値を分けると大変なので、最初に発生したエラーを返却するのが一般的です。
このソースも、そのように書き換えて見てください。

2024-04-02 01:20 UTC, Ryusei-Ami approved these changes
ソースがかなりスッキリして、良い感じです。
writeの後は処理が無いのでエラー時にgotoが無いですが、「エラーは一律gotoで飛ばす」というルールで、エラー時にgotoしてもOKです。

2024-04-02 01:36 UTC, merged