kadai2
ShunsukeNakamura2/test pull request #2
Opened 2024-03-21 06:30 UTC by ShunsukeNakamura2

課題2です。
レビューをお願いします。

2024-03-21 07:29 UTC, Ryusei-Ami requested changes

2024-03-21 07:29 UTC, Ryusei-Ami commented on kadai2/kadai2.c
> +/**
細かいことですが、「/**」はdoxgenコメント用の開始記法では？

2024-03-21 07:29 UTC, Ryusei-Ami commented on kadai2/kadai2.c
> +    printf("long=%05d float=%05d double=%05d\n", sizeof(long), sizeof(float), sizeof(double));
この課題でprint文を2つに分けるのはNG。
出力例は1行なので、プログラム的に書き込みが割り込まれる隙を作ってはいけない。

2024-03-21 07:46 UTC, ShunsukeNakamura2 commented on kadai2/kadai2.c
> +    printf("long=%05d float=%05d double=%05d\n", sizeof(long), sizeof(float), sizeof(double));
修正しました。
よろしくお願いします。

2024-03-21 08:46 UTC, Ryusei-Ami requested changes

2024-03-21 08:46 UTC, Ryusei-Ami commented on kadai2/kadai2.c
> +�ϐ��̃T�C�Y(�o�C�g��)��\�����Ă��������B
指摘の仕方が悪くていすいません。
以下のような感じが良いです。

/*
 *
 *
 * 
 */

2024-03-21 08:46 UTC, Ryusei-Ami commented on kadai2/kadai2.c
> +    printf("char=%05d short=%05d int=%05d long=%05d float=%05d double=%05d\n"
行が続く場合、カンマや比較演算子は行末においたほうが良いです。

2024-03-22 00:22 UTC, Ryusei-Ami approved these changes

2024-03-22 00:40 UTC, Ryuji-Aruga approved these changes

2024-03-22 03:38 UTC, merged