kadai20
ShunsukeNakamura2/test pull request #20
Opened 2024-03-29 05:44 UTC by ShunsukeNakamura2

〇課題20
指定した数値を指定した形式でファイルに追記する
プログラムを作成してください。
(パラメータnumberの値が格納するデータ型の
範囲外の値かチェックする必要はありません)
usage

usage: プログラム名 –n number –t type –f filename
options: -n number  数値
             -t type  B2|B4|F4
             B2  バイナリ2バイト
             B4  バイナリ4バイト
             F4  浮動小数 4バイト
             -f filename  ファイル名 

よろしくお願いいたします。

2024-03-29 06:50 UTC, Ryuji-Aruga requested changes

2024-03-29 06:50 UTC, Ryuji-Aruga commented on kadai20/kadai20.c
> +
このif文の処理と下にあるswitch文は処理をまとめられそうです。

2024-04-01 01:38 UTC, Ryuji-Aruga approved these changes

2024-04-01 07:59 UTC, Ryusei-Ami requested changes
課題18で指摘した「関数のマクロ化」は不要です。

2024-04-01 07:59 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +#define RETURN_FAIL_WRITE_CLOSE 5
課題19で指摘した、「エラー時のgoto」と「複合エラー発生時に、初回のエラー番号を返却」に対処してください。

2024-04-01 07:59 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +int main(int argc, char *argv[])
main()文が長すぎるので、処理を関数化しましょう。
少なくとも、引数解析処理はcheck_args()やanalyze_args()を定義した方が良いです。
「struct st_args」のような構造体を作成して、analyze_args()で引数の値を構造体に詰め込むとソースがすっきりするかと。

2024-04-01 07:59 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +            pos_t = i;
argv[++i]を直接charポインタに渡してしまえば、変数が減るのでは？

2024-04-01 07:59 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +    if(pos_n == -1 || pos_t == -1 || pos_f == -1) {
引数の重複もエラーにしてください。

2024-04-01 07:59 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +        param_number_B2 = (short)strtol(argv[pos_n + 1], &endptr, 10);
最後の引数が「-n」だったりすると、ポインタの不正アクセスになりませんか？

2024-04-01 07:59 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +    switch (param_type) {
以下の方法でswitch文を無くし、write()も1つで済ませられます。
・param_number_??のポインタを共通変数に渡す
・ sizeof(param_number_??) を1つの変数で代用
・ TYPE_??は使わない

2024-04-03 04:14 UTC, Ryusei-Ami requested changes
細かい指摘と、コーディングルールの補足のみです。

かなりキレイなソースに仕上がっていますね。
ソース量が増えても今の書き方をキープできれば、製品開発にすんなり入れると思います。

2024-04-03 04:14 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +#define MSG_USAGE "usage: プログラム名 -n number -t type -f filename\noptions: -n number  数値\n             -t type  B2|B4|F4\n             B2  バイナリ2バイト\n             B4  バイナリ4バイト\n             F4  浮動小数 4バイ
この書き方だと、ソースを読んでも出力イメージ（インデントの入り方）がわかりません。
以下のようにすると読みやすいと思います（レビューページ画面で表示するために整形しているため、メールで送られるメッセージだとコードがちょっとおかしくなるかも）。

#define MSG_USAGE \\
　　"usage: プログラム名 -n number -t type -f filename\n"\\
　　"options: -n number 数値\n"\\
　　"　　　　-t type B2|B4|F4\n"\\
　　...

2024-04-03 04:14 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +    st_args params = {NULL, NULL, NULL, 0};
補足です。
コーディング規約に以下のような記載がありますが、今の書き方で良いです。

    99 |【共通ライブラリ関連ルール】
   100 |共通ライブラリを作成する際の注意事項を以下に纏めます。今後ライブラリ関数を作成
   101 |する際は遵守お願いします。
   102 |
   103 |(1) typedef で定義した構造体メンバの取り扱いについて
   104 |  typedef で定義した構造体のメンバは、ライブラリ外で直読みせずに使用できる
   105 |  よう設計して下さい。(typedef された構造体の定義は、呼び出し元ではハンドラ
   106 |  として使用して下さい)。
   107 |  ※ 新規に作成する共通ライブラリが対象です。
   108 |
   109 |  typedef struct sample_struct_t {
   110 |          int count;
   111 |  } XXX_INFO;
   112 |
   113 |  XXX_INFO info;
   114 |  int my_count;
   115 |
   116 |  my_count = info.count;           /* NG: ハンドラのメンバを直読みしてはダメ */
   117 |  my_count = xxx_get_count(&info); /* OK: getter/setter を介してデータを授受 */

＜理由＞
製品のソースでも、上記は守られていません。
getter/setter の使用も任意にしています。
これは、C言語の利便性を損なわない（可読性、保守性を優先する）ための措置です。
ただし、ライブラリのハンドラの中身を直接参照するようなことはしません。

2024-04-03 04:14 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +#define ARGC 7
なんのARGC？
コメントは不要だが、用途が判るような名前にして欲しいです（流石にこれは意味がとれない）。

2024-04-03 04:14 UTC, Ryusei-Ami commented on kadai20/kadai20.c
> +    args_val->type = NULL;
args_valを初期化するのだったら、memsetで一気に全部初期化したほうが良いのでは？

2024-04-05 08:48 UTC, Ryusei-Ami approved these changes

2024-04-08 05:10 UTC, merged