Kadai daemon
ShunsukeNakamura2/test pull request #21
Opened 2024-04-01 06:46 UTC by ShunsukeNakamura2

〇追加課題(デーモン)
起動時にメッセージを出力し、
10秒後メッセージを出力して終了するデーモンを作成

よろしくお願いします。

2024-04-01 08:36 UTC, Ryusei-Ami requested changes
教科書を解釈しコーディング出来ているポイントはGoodです。
指摘について質問がありましたら、ご相談ください。

2024-04-01 08:36 UTC, Ryusei-Ami commented on kadai_daemon/daemond.c
> +	while(1) {
課題の条件を満たすだけならsleep()で良いはず。

2024-04-01 08:36 UTC, Ryusei-Ami commented on kadai_daemon/daemond.c
> +	umask(0);
umask(0)は、このデーモンがファイルを作成しないのであれば、不要。

2024-04-01 08:36 UTC, Ryusei-Ami commented on kadai_daemon/daemond.c
> +	int openmax = OPEN_MAX;
ここは、return OPEN_MAXにしたほうがシンプル。
#endifは、最後のreturnまで囲う。これで、if文が一つ減らせる。

2024-04-01 08:36 UTC, Ryusei-Ami commented on kadai_daemon/daemond.c
> +	if(openmax != -1) {
原則として、可能な限り先にエラー処理をしてください。
なので、ここはopenmax == -1を先に判定。

2024-04-01 08:36 UTC, Ryusei-Ami commented on kadai_daemon/daemond.c
> +		printf(MSG_FORK_ERROR, strerror(errno), errno);
この課題から、正常系はSTDOUT, 異常系はSTDERRに出力しましょう。

2024-04-02 01:38 UTC, Ryusei-Ami requested changes
ほぼOKです。
追加の指摘が修正されたら、approveします。

2024-04-02 01:38 UTC, Ryusei-Ami commented on kadai_daemon/daemond.c
> +	fprintf(stdout, "start:%s\n", ctime(&time_start));
間違いでは無いですが、prinftf()で良いです。

2024-04-02 01:38 UTC, Ryusei-Ami commented on kadai_daemon/daemond.c
> +		} else {
elseを書いても書かなくても同じ場合は、基本的に書かない。

2024-04-02 02:03 UTC, Ryusei-Ami approved these changes

2024-04-03 00:59 UTC, Ryuji-Aruga approved these changes

2024-04-05 03:13 UTC, merged