Kadai socket
ShunsukeNakamura2/test pull request #22
Opened 2024-04-05 04:51 UTC by ShunsukeNakamura2

〇追加課題 ソケット
１．開発内容
指定した引数に応じて、以下の動作を行うコマンドを開発してください。
①指定したファイルのデータを読み込み、相手に送信する。
②受信したデータを、指定したファイルに追記する。

２．USAGE
引数に応じて、以下の2パターンで動作させてください。
①データ送信
utltrandata -s portno -h hostname -f filename
	-h hostname 指定されたホストに対して接続します。
	-s portno  指定されたポート番号に対して接続します。
	-f filename 指定されたファイルからデータを読み込みます。
②データ受信
utltrandata -r portno -f filename
	-r portno  指定されたポート番号で接続を待ちます。
	-f filename  指定されたファイルにデータを追記します。

３．注意
・コード変換は不要です。
・必要な時にはソケットへの読み書きをリトライして下さい。
・データ読み込み前には、selectで読み込み可能か確認してください。
・エラー時は標準エラーに何が発生したのか分かるようにメッセージを出力してください。
・開発環境両方から通信ができるようにしてください。

追加として、受信側のデーモン化の要求があります

よろしくお願いします

2024-04-05 08:37 UTC, Ryuji-Aruga commented on kadai_socket/utltrandata.c
> +				break;
エラーの場合にリトライするのは、なぜでしょうか？

2024-04-05 08:37 UTC, Ryuji-Aruga commented on kadai_socket/utltrandata.c
> +	if(rc < 0) {
selectは下のwhile分の中に入れなくて大丈夫ですか？

2024-04-05 08:37 UTC, Ryuji-Aruga commented on kadai_socket/utltrandata.c
> +	if(rc < 0) {
selectはwhile分の中になくても大丈夫ですか？

2024-04-05 08:41 UTC, Ryuji-Aruga commented on kadai_socket/utltrandata.c
> +			}
エラーの場合にリトライするのは何故でしょうか？

2024-04-08 02:37 UTC, Ryusei-Ami requested changes
selectやリトライについては、有賀さんの指摘対応後にチェックするので、今回は指摘しません（修正後にレビューします）。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +#define MSG_FILE_ERROR "file %s error\n"MSG_ERROR_COMMON
エラーメッセージが増えてきて管理が煩雑になってきたので、直感的に系統が判るようにしましょう。
MSG_ERR_FILEOPEN, MSG_ERR_GET_OPEM_MAX みたいprefixを統一すると、可読性が上がります。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +		printf(MSG_USAGE);
USAGEもstderrにしたほうが良いです。
stdoutで出力するものは正常系の出力だけと考えてください。
標準出力だけリダイレクトして実行した際にUSAGEが記録されると、ツールとしては使いにくいという思想です。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +
この空行は不要。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	int main_rc = RETURN_NORMAL_END;
この変数は不要では？

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	params->hostname = NULL;
初期化するなら、全部初期化したほうがよい。
なぜportnoだけ初期化していないのか、modeは1から使用しているのに何故-1をセットしている必要があるのかが不明だが、特別な理由がない限りmemsetで0セットしたほうがわかりやすい。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +			if(++i == argc) {
書き方として間違ってはいないのだが、ガード処理は「==」よりも「>=」のように（害がかければ）広めにとるのが一般的。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	if(params->mode == MODE_SEND) {
数値比較で同じ変数を2回以上比較するのであれば、switch文にしたほうが良いです。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	int buf;
buf, bufferはchar型配列やvoid型で確保するのが一般的との認識なので、int型の一時領域にこの名前をつけられると読み手が混乱します（経験上の感覚です）。
用途がポート番号の一時格納領域ならば、tmp_portnoとかのように変数名から型や用途が類推できるようにしてください。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> + * @bfief 受信側のソケットを準備し、ファイルディスクリプタを返す
briefのスペルミス。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +static int recv_listen(unsigned short portno)
動作と関数名が乖離しており、保守性が下がる（障害作り込みの要因になるので、やっちゃ駄目）。
prepare_recv_socket()とかにしてください（「ソケットの準備」なら、bind()やlisten()しても違和感が無い）。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	int is_fail = 0;
この関数にis_fail変数は不要なはず。
極力このような変数を使わずに関数を作れるようにしてください。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	int is_fail;
is_failを使わないように修正おねがいします。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	if(sock_fd > 0) {
開いた順番とは逆順に閉じる癖をつけてください。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +		if(rc == -1) {
二重クローズによる不慮の事故を防ぐために、-1とかをセットしておいたほうが良い。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	int main_rc = 0;
関数宣言時のrc用変数は、極力1つにしてください。
複数あると、一気に可読性が落ちて、重大な障害作り込み要因になります。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	rc = select(client_fd + 1, &rfds, NULL, NULL, &timeout);
デーモンの入力待ち時間3秒？
流石に短すぎませんか？（見間違いだったらすいません）。

2024-04-08 02:37 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	if(is_fail) {
単純な処理の割にはネストが深いので、少し浅くなるように修正してください。
ネストが深くなるくらいなら、ステップ数が多少増える方がよいです。

2024-04-09 07:00 UTC, Ryusei-Ami requested changes
このタイミングですいません。
close系のエラー処理について、そろそろ実務の方針に切り替えてのコーディングスタイルにして頂きたいので、その旨の指摘をしております。
ご対応、お願いします。

2024-04-09 07:00 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	case(MODE_SEND):
C言語のcase文は、「case MODE_SEND:」の用に書くのが一般的です。

2024-04-09 07:00 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +static int daemon_init()
関数名は、「動詞_名詞()」または「prefix_動詞_名詞()」にしてください。
この関数だと、init_daemon()とか。
send_process()やrecv_process()とかも、プロセスをsendしたりreceiveするわけでは無いので、ちょっと変。
run_sending_proc()とかexec_sending_proc()のように、動詞で開始してください。

2024-04-09 07:00 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	if(0 <= params.portno && params.portno <= 1023) {
これは、引数チェックですべき処理では？（デーモン化の後にチェックするのでは遅い）。

2024-04-09 07:00 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	if(rc == 0) {
可読性が下がるので、できる限り正常終了は関数の最後にくるようにしてください。
関数によって正常終了の位置がバラけていると、読み手が混乱します。

戻り値が異常系しかない関数とかは、例外です。

2024-04-09 07:00 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	rc = close(outfile_fd);
すいません。
過去の課題でcloseのエラーを補足するように伝えていたので苦労しているのかと思いますので、この課題からcloseのエラーは無視してください。
今までは勉強のためにclose系のエラーも取ってもらってましたが、製品のソースでは無視しているので、今後はその方針でお願いします。
これで、同じcloseを書かなくて済むはずです。

2024-04-09 07:00 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	int main_rc = 0;
今回からclose系のエラーチェックは不要にして、rc用の変数を1つにしてください。

2024-04-09 07:02 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +			if(errno == EINTR || EAGAIN) { /* retryしてもいいエラー */
判定条件がおかしい。

2024-04-09 08:25 UTC, Ryuji-Aruga commented on kadai_socket/utltrandata.c
> +			rc = select(client_fd + 1, &rfds, NULL, NULL, &timeout);
selectを繰り返し呼び出す場合には、rfdsは毎回初期化して渡さないと
想定通りに動かない場合があると思います。

2024-04-10 03:27 UTC, Ryuji-Aruga approved these changes

2024-04-11 01:43 UTC, Ryusei-Ami requested changes
かなり実践的なソースに仕上がっていて、とても見やすくて良いと思います。
細かい指摘のみになりますが、修正お願いします。
指摘の類似箇所の修正（指摘がない部分の修正）にもご注意ください。

2024-04-11 01:43 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	if(client_fd > 0) {
ディスクリプタは0のケースがありえます。
sock_fdとか、他も同様。

2024-04-11 01:43 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	if(sock_fd > 0) {
この判定は不要では？
（このタイミングでは必ずオープンされてるはず）。

2024-04-11 01:43 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +	return rc;
この関数が必ず-1を返却する「仕様」なら、「return -1」としたほうが解りやすいです。
その場合、「rc = -1」が不要になる箇所もあるかと。

2024-04-11 01:43 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +			if(rc == 0) {
同じ値の連続比較なら、else if を使ったほうが読みやすいです。

2024-04-11 01:43 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +			} else {  /* retryしても復旧できないエラー */
可読性向上のため、書かなくてもよいelseは除去して、ネストを一つ上げてください。

2024-04-11 01:43 UTC, Ryusei-Ami commented on kadai_socket/utltrandata.c
> +		if(read_size == 0) {  /* 読み込むデータがなくなった */
ここはelse ifが良いです（類似あり）。

2024-04-12 04:16 UTC, Ryusei-Ami approved these changes

2024-04-17 00:32 UTC, merged