kadai:wcount
ShunsukeNakamura2/test pull request #23
Opened 2024-04-08 05:09 UTC by ShunsukeNakamura2

〇最終課題
単語カウントプログラム wcount

ひとまず、全体的な骨組みのみ作成しました。
レビューをお願い致します。

2024-04-08 06:29 UTC, Ryusei-Ami requested changes
とり急ぎ、大きな部分の指摘を出しました。
大きな関数のフローが変わるはずなので、修正後に再確認します。

2024-04-08 06:29 UTC, Ryusei-Ami commented on wcount/wcount.c
> +#define RC_ARG_ERROR 		1
ソケットの課題の指摘と同様の対処をしてください。

2024-04-08 06:29 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static int input_mode_process(st_args params);
関数名は、「動詞_名詞()」または「prefix_動詞_名詞()」にしてください。
この「input」は関数動作の動詞ではありません。
関数動作を最初にするなら、proc_input_request()とか？

2024-04-08 06:29 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static int input_mode_process(st_args params)
複雑な関数は、まず以下のようにするとある程度片付きます。
・初期化処理（init_())　// メモリ割り当てやファイルオープンは纏めてしまうと良い
　→ 初期化処理で準備するものは構造体に纏めると良いです
・メイン処理（ここはいくつかの関数で構成）
・終了処理（開放しか無いならfree_() 、close()系やfree()系が混在ならfinalize_()）

2024-04-08 06:29 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	root = make_new_word(NULL, 0);
このレベルの階層からならば、WordData単体ではなくリストとして扱うべき。
rootはmake_new_word()と単体で作っているのに、解放はfree_list()になっているので、対であることが分からず直感的でない。
対になる関数は、パッと見てそのことが判ることが望ましい。
あと、listを扱うのであれば、名前に規則性を持たせて、同一のオブジェクト（構造体）にアクセスしていてどういう操作がされるのかが直感的になるよう意識すると可読性が向上する。

2024-04-12 01:08 UTC, ShunsukeNakamura2 commented
wcount -i infile (入力モード，databaseなし)
の機能を作成しました。
実装箇所は

analyze_args() :引数解析
proc_input_request() :mainから呼ばれる入力モード時の処理 (database関連は未実装)
init_proc_input_request() :proc_input_request()の初期化処理
finalize_proc_input_request() :proc_input_request()の終了処理
make_WDList_from_infile() :構造体リスト操作関連
create_WD() :構造体リスト操作関連
init_WDList() :構造体リスト操作関連
disp_WDList() :構造体リスト操作関連
free_WDList() :構造体リスト操作関連
add_to_WDList() :構造体リスト操作関連
search_last_newline() :utility, make_WDList_from_infile()で使用
get_token() :utility, make_WDList_from_infile()で使用

です。
よろしくお願いします。

2024-04-12 05:37 UTC, Ryusei-Ami requested changes
ソケットの課題でされた指摘と同じ問題が混ざっているので、対処お願いします。

ざっと見た感じで指摘している部分もあるので、指摘がおかしかったらご連絡ください。
ただ、この課題では極力無限ループは使わないで欲しいです（無限ループの方が良いということであれば、次回レビュー時に改めて確認させて頂きます）。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	for(i = 0; i < argc; i++) {
不正なオプションが来た場合はエラーにしてください。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> + * @bfief コマンドライン引数をチェックしパラメータをparamsに入れる
スペルミス。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		finalize_proc_input_request(init_data);
エラー時の終了処理が各所に散らばる書き方は避けてください（製品ソースでも散見されますが、アンチパターンです）。
この関数ならば、init処理のエラーでのreturn以外は関数の最後のエラーに寄せてください。
エラー時のfinalize処理も、1箇所（末尾）に纏めてください。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		return RC_NORMAL_END;
関数の戻りが
　return error;
　return normal;
　return error;
　return normal;
になるようなコーディングは、可読性が下がるので避けてください。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static int init_proc_input_request(InputModeData *init_data, CmdParams params)
「InputModeData *init_data」は、別の関数では「InputModeData *finalize_data」になっていますが、同じオブジェクトを扱うのであれば、同じ名前にしてください。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	if(finalize_data->fd_infile > 0) {
ソケットの課題の指摘と同様。類似あり。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		last_newline_pos = search_last_newline(read_str, (int)size + skipped_str_len);
strtokとか使えば、もう少しシンプルになるのでは？

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		while(1) {
無限ループの利用は必要最小限にしてください（読み手は、常駐デーモンのような処理を想起します）。
大抵は終了条件を定義できるはず。

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		get_token(read_str, &token);
strtokに似た関数を再作成してませんか？

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	char read_str[INFILE_LINE_MAX] = {0};
一行の上限が1024なのに、INFILE_LINE_MAXが1024では駄目なのでは？

2024-04-12 05:37 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		memmove(read_str, read_str + last_newline_pos + 1, skipped_str_len);
whileの中身がごちゃごちゃしていて解りにくいです。
例えば以下のように出来ませんか？

1) 1行取得（1025文字以上の行があったらエラーを返却）// 多めに読み込んだ分はキープ
2) 単語を取得
　→ 取得できたら追加とか実施

1) の部分がベタ書きされているので、関数化するとスッキリすると思いました。

2024-04-17 08:51 UTC, Ryusei-Ami requested changes
一旦、ここまでで修正お願いします。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		break;
現在の作りでここに来ることはありえないのだが、これが製品だったらガード処理を入れる。
自分だったら、「バグ以外でここに来ることはありえない」とのコメントを書いた上で、システムエラーにします。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		} else if(*argv[i] == '-') {
これだと、「./wcount -i infile hoge」とかでエラーにならないのでは？

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	for(i = 0; i < argc; i++) {
argv[0]って、見る必要があるデータ入ってましたっけ？

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	InputModeData initialized_vars;
変数名は自由ではあるのですが、長い名前をつけるなら内容が判る名前にして欲しいです。
initialized_varsは「初期化された変数群」と解釈しましたが、以下の理解です。
・「初期化された」→ それはそうだろ。。。
・ 「変数群」→ 構造体なのだから自明
つまり、この名前から得られる情報がありません。
オブジェクトの用途を解釈して名前をつけると良いです。
意味的にはinput_dataとか、かな？　似たようなdisp_dataができるはずなので。
（ちょっと、自分で考えて見てください）。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	if(rc != RC_NORMAL_END) {
このif文は、L215のifの外に出しちゃ駄目です（L215のifに入らないのであれば、不要な判定）。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static int init_proc_input_request(InputModeData *init_data, CmdParams params)
特に理由がない限り、同じオブジェクトの変数名は揃えてください。
前段の指摘で、InpuftModeDataの変数名をinput_dataにしたら、ここも同じにすると可読性が向上します。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		init_data->fd_database = -1;
他のgoto endではfd_databaseに-1をセットしていないことに違和感があります。
これが不要なのか、他が足りてないのか。
他が足りてないなら、セットするタイミングはここではないかと。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	init_data->fd_database = open(params.database, O_RDWR | O_CREAT,
L276-282の処理はL272をif(params.db_flag) にして、そのパラグラフ配下に入れたほうが可読性と保守性があがります（ネストは1つ下がりますが）。

現状だと、L276以降にはDBフラグありの処理しか入らず、endの前に共通処理がかけません。
更にgotoで飛ぶケースが 正常/異常 のパターンに分かれるので、読みにくいです（goto処理を異常系とみなして読むことが多いです）。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	rc = init_proc_input_request(&initialized_vars, params);
proc_input_request() のprocは、「要求データを処理する」の動詞部分なので良いですが、ここのprocは不要では？
単純にinit_input_data() とかのほうがシンプルかと。
（init_input_request() って書くと、入力要求の初期化ですが、入力要求の初期化もしてないので）。
finalizeも同様。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static int proc_disp_request(CmdParams params)
proc_input_request() の指摘と同様の問題があるので、修正お願いします。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> + * @brief proc_disp_request()で使用するfdのopne、構造体リストの作成を行う
誤字「opne」

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> + * @brief proc_input_request()で使用するfdのopne、構造体リストの作成を行う
誤字「opne」

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	is_little_endian = *(char *)&is_little_endian;
複数箇所で同じ処理をしているのが、気になります。
bswap_32()の処理を関数化して、その中で is_little_endianとかをstatic定義すれば、一箇所に纏めつつ計算1回に纏められないでしょうか？

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	while(length != 0 && rc == RC_NORMAL_END) {
「rc == RC_NORMAL_END」を先に判定したほうが良いです。rcが異常系の場合、lengthを見ても意味が無いので。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		word = (char*)malloc(length);
mallocはキャスト不要です（よく見かけますが）。
このキャストが必要になるのはC++のコンパイラを使う場合か、太古のコンパイラを使用する場合のみです。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static int get_word_from_database(int fd_database, char *database, char *word, int length)
out引数は、最初か最後に寄せてください。
自分は、memcpy()みたいな関数だったらout変数は先頭に、それ以外の場合は末尾に持っていくことが多いです。
例外として、WordData rootみたいに基点とするin/outオブジェクトを多少する場合は、これを先頭に固定して関数を量産します（その方が、頭が整理される）。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		new_word = create_WD(&token, count);
L436～L442の流れと全く同じ処理が他にあるので、add_word_to_WDList(root, word, length)みたいな処理があれば良さそうに見えました。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	WordData *new_word;
wordはcharで、new_wordはWordDataなので、読むのがしんどい。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		word = (char*)malloc(length);
create_WD()の中でword領域作り直すのだったら、元データはdatabaseのポインタで良いのでは？

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	new_WD->word = (char*)malloc(token->length);
malloc() and memcpy() だったら、strdupで良いのでは？

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	while(rc != RC_READ_END) {
私が過去にif ((rc = func()) == 0)みたいな書き方をNGにしたせいだと思うのですが、ここは
while ((rc = get_line()) == RC_NORMAL_END)にしてください。

元々デバッグのしやすさとかを意識した指摘ですが、whileの前後に同じ処理を書くよりは、whileの中に関数を書いた方が解りやすいので。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	rc = get_line(fd_infile, infilename, line, &skipped_len);
lineをコントロールする変数を外に持つのはやめてください。関数の仕様が複雑になります。
lineとskipped_lenが切り離せない存在で、個々に操作してはいけないものであるならば、一つに纏めてハンドル化してください。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	StrSplitter str;
strって変数名は、通例char *str的なものと解釈されがちなので、オブジェクトっぽい名前にして欲しいです。

2024-04-17 08:51 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		get_token(&str, &token);
一行読み込んだデータをstruct line_bufferとかに入れて、token = get_token(line_buffer, token)とかで取得してwhile((token = get_token()) != NULL)とかで回せるとキレイな感じになりそうな気がするのですが。

2024-04-18 02:50 UTC, ShunsukeNakamura2 commented on wcount/wcount.c
> +		} else if(*argv[i] == '-') {
不正なオプションをエラーにするという指摘だったのでこのような実装にしています。
オプションを伴わないパラメータもエラーにするように直します。

2024-04-18 05:34 UTC, ShunsukeNakamura2 commented on wcount/wcount.c
> +		init_data->fd_database = -1;
finalizeでcloseする前に、値を初期化しておく必要があるため、ここで-1をセットしています
値をセットするタイミングは迷ったのですが、以下の考えで現在の記述にしました
・案1．呼び出し元のproc_input_request()で初期化
InputModeData input_data = {NULL, -1, 0};
これはfd_databaseのみに-1をセットしているのが不自然に見えた

・案2．呼び出し元のproc_input_request()で初期化 その2
InputModeData input_data = {NULL, -1, -1};
fd_infileに必要のない-1初期化をしている

・案3．init_proc_input_request()の頭で初期化
頭で唐突に-1をセットするよりも、実際に必要になった時に値を入れた方が自然だと思った

2024-04-18 05:55 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		init_data->fd_database = -1;
意図理解しました。
自分なら案3ですね。可能な限り、条件分岐後の値挿入は避けるようにしています。
よくエラーケースの値セット漏れによるコアダンプ等を見かけますが、大抵は処理を追加したときの値セット漏れです。
先頭で-1をセットしておいて、処理されなければその値が使用されるようにしておけば、処理を追加する際に余計なことを考えずに済むので、保守性が上がります。

2024-04-23 05:05 UTC, Ryusei-Ami requested changes
一通りレビューしましたので、修正お願いします。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static int init_input_data(InputModeData *init_data, CmdParams params);
関数定義と実関数の引数名が異なっています。
製品開発時にもよく見かけるケアレスミスですが、エディタの一括置き換えを使うと再発防止出来ます。
ただし、置き換えは一件づつ目視確認しながらやらないと、意図しない置き換えで苦しむことになるのでご注意ください。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		close(input_data->fd_infile);
二重クローズによるコアダンプを防止するために、クローズしたディスクリプタには-1をセットしてください。他も同様。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		close(disp_data->fd_database);
二重close防止対策漏れ。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> + * @param[in] root         WordDataリストの先頭要素のアドレス
関数コメントの引数の順番は、実関数の引数の順番と揃えてください。
類似があれば、同様に修正してください。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		length = strlen(current->word) + 1;
同じstrlenを2回するくらいなら、length_be変数定義した方が良いです（全く同じ処理を繰り返してたので、一瞬書き間違えかと思いました）。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		count = bswap_little_endian(current->count);
上の指摘でlength_be追加すると思いますが、合わせてここのcountもcount_beとかにしたほうが良いです。
エンディアン固定している変数は、変数名から判るようにしておくと、後に誤用されるリスクが減ります。
（余談ですが、こういう部分の誤用はテストでもスルーされて、リリース後の運用で大問題に発展する場合があります）。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> + * @para,[in]	  infile      読み込み対象のファイル名
「para,」→誤字

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	while((rc = get_chunk(fd_infile, infile, &chunk)) != RC_READ_END) {
NORMAL_ENDの場合にのみwhileループに入るようにすれば、L519で毎回rcを判定しなくて済むのでは？
L518で判定しているrcを、L519でループの都度判定するのは少し無駄に感じます。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		while((p_token = get_token(&str_splitter, &token)) != NULL) {
この使い方でしたら、chunkとstr_splitterは分割してはいけません。
str_splitter.target（ポインタ）がchunk.str（実体）を指してますが、実際の開発だと、このことを知らずにchunk.strが解放されてstr_splitter.targetの参照でSIGSEGVみたいなことが起こり得ます。

実際の開発でしたら、chunkとstr_splitterを一つに纏めた構造体を作って操作すると思います。
構造体内で完結していれば、保守性が上がり、問題が起きにくくなるはずです。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		while((p_token = get_token(&str_splitter, &token)) != NULL) {
get_token()ですが、&tokenを渡してp_tokenとしてtokenのポインタを受け取るような書き方はNGです。
&tokenとp_tokenが同じものであることが直感的では無いため、保守性が下がり、障害作り込みの要因になります。
解決例は2案あります。

1) p_token = get_token(..., p_token)
　→ 渡したp_tokenに値が入って返ってくることが自明

2) rc = get_token(..., &token)
　→ 正常終了なら、tokenに値が入れられるであろうことが想像出来る（&で渡しているので）

ちなみに、get_token(..., p_token)だと、関数コメント見ないと参照渡しなのか、値が返ってくるのか判らないので、ちょっと使いにくくなります。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	WordData *new_WD = calloc(sizeof(WordData), 1);
（結果は同じなのですが）引数の順番が逆です。製品でも同じミス見かけますが。

void *calloc(size_t nmemb, size_t size);
man抜粋：calloc()  関数は  size   バイトの要素   nmemb   個からなる

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	WordData *new_WD = calloc(sizeof(WordData), 1);
変数定義で、成否が発生する処理を実施しないでください。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	return create_WD(NULL, 0);
ここではcreate_WD()を再利用しないほうが良いです。
create_WD()のL554で、
if(token == NULL) {
ってやってて、最初理由がわかりませんでした。
create_WD()の保守性が下がるので、ここをcalloc()するだけの処理にしたほうが、双方の関数の結合度が疎になるので良いかと。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> + * @param[out] new_WD       実態を作成するWordData構造体ポインタのアドレス
「実態」→誤字

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	*new_WD = calloc(sizeof(WordData), 1);
他のcallocの指摘と同様。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		free(*new_WD);
これが必要になることは無いはず。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +static Token *get_token(StrSplitter *str_splitter, Token *token)
（阿見備忘録）L525の指摘で大きめの修正がされるはずなので、修正後に再確認。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		head_ptr++;
保守性や可読性の観点から、while内のカーソル移動は変数1個にしたほうが良いです。
whileループ内で必要なのはptrカーソルだけなので、そこだけ移動して、whileを抜けたらカーソルと基点の差分を取ればlength等の計算は1回に収まるはず。

ループで複数の変数をインクリメントしている箇所については、本当にそれが必要か見直してください。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	char *head_ptr;
head_ptrは、常にヘッドではないような。。。
もし、head_ptr（意味：文字列の先頭ではない）みたいな変数名だと、バグの温床になります。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	size = read(fd_database, length, sizeof(int));
変数が1個増えますが、lengthとlength_beは変数分けたほうが良いです。
ぱっと見、lengthの中身がlittle endianかbig endianか判らないので、変数分けると誤り防止になります。

「設計書見ればわかるでしょ？」みたいなことを思うかもですが、実務ではそれが相手に期待できないことも多いので、簡単な工夫でミスを防止できるなら、そうした方が良いです（こういう気遣いが出来るエンジニアは稀ですが。。。）

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	last_newline_pos = INFILE_LINE_MAX - chunk->skipped_len - 1;
変数宣言の後に1行空行を入れると、ぐっと読みやすくなります。
（Linuxのカーネルソースとかはそうなっているので、読みやすいです）。

2024-04-23 05:05 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	size = read(fd_infile, chunk->str + chunk->skipped_len, INFILE_LINE_MAX - chunk->skipped_len);
入力ファイルのサイズがINFILE_LINE_MAX丁度で、最後の改行位置が例えば1000バイト目とかの場合、skipped_len > 0で読み残しがある状態で、read()の結果sizeが0になって、読み残しが発生したりしませんか？

2024-04-25 02:02 UTC, Ryusei-Ami requested changes

2024-04-25 02:02 UTC, Ryusei-Ami commented on wcount/wcount.c
> + * @param[in]   対象のリストの先頭要素のアドレス
引数名が抜けてます。

2024-04-25 02:02 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	while((rc = get_chunk(fd_infile, infile, &str_splitter.chunk)) == RC_NORMAL_END || rc == RC_READ_END) {
READ_ENDを返しているのにループ処理を継続する必要があるという関数仕様が歪です（製品開発でこれをされると、危うさを感じます）。
自分だったら、get_chunk()の結果、処理するデータがある場合にのみNORMAL_ENDを返す仕様にします。

2024-04-25 02:02 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	if(str_splitter->offset == INFILE_LINE_MAX) {
関数が-1を返却する場合、異常終了すべきエラーが返却されたと解釈するのが一般的ですが、ここでは正常終了かつ処理継続可能な状態として-1を返却していますので可読性と保守性が低くなります。
これだったら、p_token = get_token(..., p_token) にして、単語が無いならNULLリターンしたほうが直感的です。

2024-04-25 02:02 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		if(++i == INFILE_LINE_MAX) {
current_ptrは関数の前段からインクリメントしているのに、何故iは0からインクリメントして問題ないのか理解出来ませんでした。current_ptrがchunk_strの末尾に到達したら終わりって話なら、「current_ptr >= end_ptr」でbreakさせた方が直感的です。
そして、ここでbreakしたとして、current_ptrはchunk_strの末尾っぽいですが、INFILE_LINE_MAXで割り当てたサイズ+1の位置の\0を期待した動作になってないですよね？（これは、追うのが大変なので、確認です）。

2024-04-25 02:02 UTC, Ryusei-Ami commented on wcount/wcount.c
> +	str_splitter->offset += current_ptr - start_ptr;
「offset = current_ptr - chunk.str」の方が直感的（今の書き方だと理解するのに2手必要だが、これだと1手で理解できる）。

2024-04-25 02:02 UTC, Ryusei-Ami commented on wcount/wcount.c
> +		return RC_READ_END;
chunk->strに改行ありの読み残しがあったらreadせずにreturnして、そうでない場合にreadするようにすれば、一回のread() でread() == 0 の場合に残データなしでREAD_ENDできるのでは？
そうすれば、この関数の戻りがRC_NORMAL_ENDの時だけwhileの中に入れば良くなって、関数の使い回しが良くなると思います。

2024-04-26 01:18 UTC, Ryusei-Ami approved these changes
阿見のPGはOKです。
有賀さんのapproveとPT完了を以って、完了としてください。

全体的によく書けていますので、自信を持って今後の開発に臨んでください。
敢えて言えば、get_chunk() はもう少しブラッシュアップできそうなところですが、此処から先は実際のPGで意見交換できればと思います（課題としては十分な出来ですので、これ以上の指摘はありません）。

2024-04-26 01:29 UTC, Ryuji-Aruga approved these changes

2024-04-29 23:39 UTC, merged