kadai8
ShunsukeNakamura2/test pull request #8
Opened 2024-03-21 07:07 UTC by ShunsukeNakamura2

〇課題8
プログラムを起動してから呼び出すたびに
1インクリメントした値を返す関数を
作成してください。初期値は0とします。
(intの最大値を超えた場合の動作を
考慮する必要はありません)

関数プロトタイプ
int static_counter(); 

よろしくお願いします。

2024-03-22 02:05 UTC, Ryusei-Ami requested changes

2024-03-22 02:05 UTC, Ryusei-Ami commented on kadai8/kadai8.c
> +int static_counter();
static関数にしてください。

2024-03-22 02:05 UTC, Ryusei-Ami commented on kadai8/kadai8.c
> +        printf("%d\n", static_counter());
関数の戻り値をそのままprint文に渡さないでください。
関数の引数に関数を設定するのは、基本的にNGと理解してください。
（getter関数を出力処理の関数に渡すことを許可する場合が稀にあります）。

2024-03-22 02:05 UTC, Ryusei-Ami commented on kadai8/実行結果.txt
> +0
初期値が0で呼び出すたびに1インクリメントした値が返されるなら、最初は1では？

2024-03-22 05:08 UTC, Ryuji-Aruga approved these changes

2024-03-22 05:34 UTC, Ryusei-Ami requested changes

2024-03-22 05:34 UTC, Ryusei-Ami commented on kadai8/kadai8.c
> +    return ++count;
インクリメントは一般的に、特に理由がなければ「count++」（後加算）で記述します。
（結果は同じなのですし、大抵の人は注意しませんが、なにも言わずに警戒レベルを上げられてしまいます）。

2024-03-25 02:12 UTC, Ryusei-Ami approved these changes

2024-03-25 02:17 UTC, Ryusei-Ami commented on kadai8/kadai8.c
> +    return ++count;
すいません。指摘、勘違いしてました。
一行省略するための前加算ですね。
再修正は不要ですが、「retunr ++count」は理由のある前加算なので、正解でした。

2024-03-25 03:08 UTC, merged